name: feedays
description: Mobile frontend for RSS reader service.

publish_to: "none"

# 以下は、アプリケーションのバージョンとビルド番号の定義です。
# バージョン番号はドットで区切られた3つの数字で、1.2.43のようなものです。
# その後に、オプションでビルド番号を + で区切って指定します。
# flutter buildでは、バージョンとビルダー番号の両方を、それぞれ--build-nameと--build-numberを指定して上書きすることができます。
# Androidでは、build-nameがversionName、build-numberがversionCodeとして使用されます。
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# iOS では build-name は CFBundleShortVersionString として、build-number は CFBundleVersion として使用されます。
# iOS のバージョン管理について詳しくは以下を参照してください。
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Windowsでは、製品やファイルのバージョンのメジャー、マイナー、パッチ部分としてbuild-nameが、ビルドサフィックスとしてbuild-numberが使用されます。
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 追加
    sdk: flutter # 追加
  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  responsive_framework: ^1.1.1
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^2.3.2
  drag_and_drop_lists: ^0.3.3
  infinite_scroll_pagination: ^4.0.0
  functional_widget: ^0.10.1
  mockito: any
  sliver_tools: ^0.2.9
  page_transition: ^2.0.9
  http: any
  html: any
  ogp_data_extract: ^0.1.2
  metadata_fetch: ^0.4.1
  string_validator: ^0.3.0
  # このプラグインが原因で最新のXcodeではビルド出来ない
  # cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  universal_platform: ^1.0.0+1
  flutter_html_all: ^3.0.0-alpha.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  webview_flutter: ^4.4.2
  share_plus: ^7.2.1
  numberpicker: ^2.1.1
  flutter_picker: ^2.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  device_info_plus: ^9.1.1
  network_info_plus: ^4.1.0
  webfeed_revised: ^0.7.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.8

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1
  pedantic_mono: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/dialog/

  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
